version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: lesson-db
    restart: always
    environment:
      MYSQL_DATABASE: lesson_platform
      MYSQL_USER: lesson_app
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "Janghun7926*"
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: lesson-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/lesson_platform?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: lesson_app
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_SQL_INIT_MODE: always