spring:
  application:
    name: lesson-matching-platform

  # Datasource Configuration
  datasource:
    url: jdbc:mysql://localhost:3308/lesson_platform?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: root
    password: Janghun7926*

  # JPA Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  # SQL Init
  sql:
    init:
      mode: always

  # Redis
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017/lesson_chat

  # Security OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:임시_클라이언트_아이디}
            client-secret: ${GOOGLE_CLIENT_SECRET:임시_클라이언트_시크릿}
            scope: profile, email

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  querydsl:
    enabled: false

# JWT
jwt:
  secret: ${JWT_SECRET:temp_jwt_secret_key_which_is_long_enough_to_be_secure_32_bytes}
  access-token-expiration: 900000       # 15분 (ms)
  refresh-token-expiration: 604800000   # 7일 (ms)

# Toss
toss:
  payments:
    secret-key: ${TOSS_SECRET:temp_toss_secret_key}
    confirm-url: https://api.tosspayments.com/v1/payments/confirm

# LangChain4j
langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY:temp_openai_api_key} # 발급받은 API 키
      model-name: gpt-4o-mini   # 속도가 빠르고 비용이 매우 저렴한 모델
      temperature: 0.2
    embedding-model:
      api-key: ${OPENAI_API_KEY:temp_openai_api_key}
      model-name: text-embedding-3-small