spring:
  application:
    name: lesson-matching-platform

  # Datasource Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/lesson_platform?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: root
    password: Janghun7926*

  # JPA Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  # SQL Init
  sql:
    init:
      mode: always

  # Redis
  data:
    redis:
      host: localhost
      port: 6379

  # Security OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:임시_클라이언트_아이디}
            client-secret: ${GOOGLE_CLIENT_SECRET:임시_클라이언트_시크릿}
            scope: profile, email

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  querydsl:
    enabled: false

# JWT
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900000       # 15분 (ms)
  refresh-token-expiration: 604800000   # 7일 (ms)